CREATE TABLE IF NOT EXISTS books (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  rating INTEGER NOT NULL,
  available BOOLEAN NOT NULL DEFAULT false,
  url TEXT UNIQUE NOT NULL,
  scraped_at TIMESTAMP DEFAULT NOW()
);